trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: PrintHello
  jobs:
  - job: PrintHelloWorld
    steps:
    - script: echo "Hello World"
      displayName: 'Print Hello World'

  - job: PrintHelloSpace
    dependsOn: PrintHelloWorld
    steps:
    - script: echo "Hello Space"
      displayName: 'Print Hello Space'

- stage: DeleteHelloWorld
  jobs:
  - job: DummyJob
    steps:
    - script: echo "This is a dummy job with no actual tasks."
      displayName: 'Dummy Job'


